# AUTOGENERATED! DO NOT EDIT! File to edit: 01_data_prepocess.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'nlp_en']

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# Cell
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import os
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_colwidth', -1)
from nltk import sent_tokenize
import nltk
# import gensim
import string
from spacy.lang.en import English
from spacy.lang.en.stop_words import STOP_WORDS
from tqdm import tqdm
import spacy
import re
nlp_en = spacy.load("en_core_web_sm")